BOARD_SIZE = 9
KOMI = 0.5
MAX_TURNS = 100 # 30 # a bit plus then the total number of position to play
ROLL_OFFSET = 20

# MCTS variables
C_PUCT = 5
N_THRESHOLD = 15 
N_TREE_SEARCH = 1000 # 30
QU_RATIO = 0.5

TEMPERATURE_MCTS = 1.6
DECREACE_TEMPERATURE_MCTS = 0.97
DATABASE_SIZE = 7000 # 100 

# MCTS parallele and batch variables
MAX_PROCESSES = 1
VIRTUAL_LOSS = 3

ROLL_BATCH_SIZE = 16
MAX_WAIT_TIME = 0.04
MAX_QUEUE_SIZE = ROLL_BATCH_SIZE

# training variables
# DEVICE = 'cuda:0'
EPOCHS = 20
MOMENTUM = 0.8
LEARNING_RATE = 0.01
DECREACE_LEARNING_RATE = 0.97
MODEL_WEIGHT_TEMPERATURE = 0.03
BATCH_SIZE = 64

# loss variables
L2_LOSS = 0.01
CLASSIFICATION_LOSS = 1
REGRESSION_LOSS = 0.5
