BOARD_SIZE = 9
KOMI = 0.5
MAX_TURNS = 100 # a bit plus then the total number of position to play
ROLL_OFFSET = 20

# MCTS variables
C_PUCT = 5
N_THRESHOLD = 15 
N_TREE_SEARCH = 1000
QU_RATIO = 0.5

TEMPERATURE_MCTS = 1.6

# MCTS parallele and batch variables
MAX_PROCESSES = 1
VIRTUAL_LOSS = 3

ROLL_BATCH_SIZE = 8
MAX_WAIT_TIME = 0.04
MAX_QUEUE_SIZE = ROLL_BATCH_SIZE

# training variables
# DEVICE = 'cuda:0'
EPOCHS = 20
MOMENTUM = 0.8
LEARNING_RATE = 0.008
BATCH_SIZE = 64

# loss variables
L2_LOSS = 0.00005
CLASSIFICATION_LOSS = 1
REGRESSION_LOSS = 0.5
